import Products from "@/components/home/Products";
import ProductList from "@/components/products/ProductList";
import { fetchAllProducts } from "@/store/slices/product";
import Head from "next/head";
import Image from "next/image";
import { useDispatch } from "react-redux";
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const dispatch = useDispatch();
  dispatch(fetchAllProducts());
  return (
    <>
      <Head>
        <title>Zadicus | Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-x-hidden py-32">
        <ProductList />
      </main>
    </>
  );
}
